version: "3"

services:
  mosquitto:
    container_name: mosquitto
    build: ./mosquitto
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: always
  homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi3-homeassistant:0.83.3
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./homeassistant/config:/config
    ports:
      - "8123:8123"
    restart: always
    depends_on:
      - mosquitto
  nodered:
    container_name: nodered
    image: nodered/node-red-docker:0.19.5-rpi-v8
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nodered/data:/data
    ports:
      - "1880:1880"
    restart: always
    depends_on:
      - homeassistant
